var classes = [
    {
        "name": "LogGeral",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "log",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 28,
        "vocabulary": 17,
        "volume": 114.45,
        "difficulty": 3.96,
        "effort": 453.03,
        "level": 0.25,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 28.91,
        "number_operators": 9,
        "number_operands": 19,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 60.31,
        "mIwoC": 60.31,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "\\",
        "pageRank": 0.13,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "DadosIncompletosException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gerarLog",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 14,
        "volume": 148.49,
        "difficulty": 3.14,
        "effort": 465.71,
        "level": 0.32,
        "bugs": 0.05,
        "time": 26,
        "intelligentContent": 47.34,
        "number_operators": 16,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 3,
        "loc": 21,
        "lloc": 18,
        "mi": 84.91,
        "mIwoC": 57.28,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "package": "\\",
        "pageRank": 0.18,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "PesoExcedidoException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gerarLog",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 14,
        "volume": 148.49,
        "difficulty": 3.14,
        "effort": 465.71,
        "level": 0.32,
        "bugs": 0.05,
        "time": 26,
        "intelligentContent": 47.34,
        "number_operators": 16,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 57.28,
        "mIwoC": 57.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "package": "\\",
        "pageRank": 0.18,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "AlturaExcedidaException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gerarLog",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 14,
        "volume": 148.49,
        "difficulty": 3.14,
        "effort": 465.71,
        "level": 0.32,
        "bugs": 0.05,
        "time": 26,
        "intelligentContent": 47.34,
        "number_operators": 16,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 57.28,
        "mIwoC": 57.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "package": "\\",
        "pageRank": 0.18,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "ExemploException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gerarLog",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 14,
        "volume": 148.49,
        "difficulty": 3.14,
        "effort": 465.71,
        "level": 0.32,
        "bugs": 0.05,
        "time": 26,
        "intelligentContent": 47.34,
        "number_operators": 16,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 57.28,
        "mIwoC": 57.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "package": "\\",
        "pageRank": 0.18,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Usuario",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNome",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataNascimento",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPeso",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAltura",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSexo",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIdadeAtual",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fazAniversarioHoje",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dadosCompletos",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verificarPeso",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verificarAltura",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 9,
        "ccnMethodMax": 6,
        "externals": [
            "DateTimeInterface",
            "SexoEnum",
            "DateTimeInterface",
            "SexoEnum",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "ExemploException",
            "DateTimeInterface",
            "SexoEnum",
            "DadosIncompletosException",
            "PesoExcedidoException",
            "AlturaExcedidaException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 71,
        "vocabulary": 23,
        "volume": 321.17,
        "difficulty": 6.81,
        "effort": 2185.76,
        "level": 0.15,
        "bugs": 0.11,
        "time": 121,
        "intelligentContent": 47.19,
        "number_operators": 22,
        "number_operands": 49,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 17,
        "loc": 83,
        "lloc": 66,
        "mi": 73.8,
        "mIwoC": 41.55,
        "commentWeight": 32.25,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.09,
        "relativeSystemComplexity": 5.09,
        "totalStructuralComplexity": 11,
        "totalDataComplexity": 45,
        "totalSystemComplexity": 56,
        "package": "\\",
        "pageRank": 0.13,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    }
]